version: "3.8"

# networks:
#   reverse_proxy:
#     external: true

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        - ENV=prod
    networks:
      - default
      # - reverse_proxy
    restart: unless-stopped
